name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.SWDV280.pem}}
          REMOTE_HOST: ${{secrets.ec2-3-93-31-85.compute-1.amazonaws.com}}
          REMOTE_USER: ${{secrets.ubuntu}}
          TARGET: ${{secrets.3.93.31.85}}
